### ISSUE TITLE
movePoints and moveSize are always zero

### ISSUE THREAD

**Issue by MarkEhr** [kazmiekr/joysticknode#1] opened 2015-11-09 15:45 UTC
Properties movePoints and moveSize are always zero when moving the joystick. I have found on line 98 of `KAZ_JoystickNode.m` which looks like this:  
`movePoints = distance / outerRadius * self.movePoints;`  
I couldn't figure out why is `self.movePoints` multiplying, so I removed it and it all worked out. So, is there a reason for that?

**Comment by kazmiekr** [comment] 2016-01-06 14:23
Hey Mark, apologize for the super late response, but I finally got around to looking at this.  I haven't touched this code in a while and had to try to remember what in the world I was doing ;)

The idea there is that you can define movePoints for your joystick, and as you move the control inside the circle, it'll scale the amount it gets moved from 0 to your movePoints.  So if you had set movePoints to 8, if you were halfway between the center of the circle and the outside edge, it'd scale that to 4.  You can change this value to whatever you like, but by default it's using 0, which may not be doing what you expect.

If you remove that piece, it won't scale the movement based on the distance from the center to the outside and just provide a constant value.

Curious if you're working on something and it's in the app store, I'd love to see it being used in the wild!

Thanks and have a great day!

Kevin

**Comment by kazmiekr** [comment] 2016-01-06 14:24
Closing this as I think this is by design, I'll reopen if I find something I need to address.

**Closed as completed by kazmiekr** 2016-01-06 14:24 UTC
